services:
  nsapp_1:
    image: nsapp
    build:
      context: .
      dockerfile: NSApp/Dockerfile
    networks:
      - nsapp_network
  nsapp_2:
    image: nsapp
    build:
      context: .
      dockerfile: NSApp/Dockerfile
    networks:
      - nsapp_network
  nsapp_3:
      image: nsapp
      build:
        context: .
        dockerfile: NSApp/Dockerfile
      networks:
        - nsapp_network
networks:
  nsapp_network:
    driver: bridge
  
